function figure_omega(X2, Y2, X3, Y3)
    %CREATEFIGURE(X2, Y2, X3, Y3)
    %  X2:  vector of plot x data
    %  Y2:  vector of plot y data
    %  X3:  vector of plot x data
    %  Y3:  vector of plot y data

    %  Auto-generated by MATLAB on 10-May-2023 07:33:01

    % Create figure
    figure1 = figure;

    % Create axes
    axes1 = axes('Parent', figure1);
    hold(axes1, 'on');

    % Create plot
    plot(X2, Y2, 'DisplayName', 'q-Newton 1', 'Marker', 'square', 'LineWidth', 1, ...
        'Color', [0 0 1]);

    % Create plot
    plot(X3, Y3, 'DisplayName', 'q-Newton 2', 'Marker', 'diamond', 'LineWidth', 1, ...
        'Color', [1 0 0]);

    % Create ylabel
    ylabel('\omega=2/(M_n+m_n)');

    % Create xlabel
    xlabel('iteration');

    box(axes1, 'on');
    hold(axes1, 'off');
    % Set the remaining axes properties
    set(axes1, 'FontSize', 24, 'XGrid', 'on', 'YGrid', 'on');
    % Create legend
    legend1 = legend(axes1, 'show');
    set(legend1, ...
        'Position', [0.796527779407592 0.142136265415693 0.103645831036071 0.156380748649023]);
